// Generated by pnpm db:types. Do not edit by hand.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  graphql_public: {
    Tables: {
      [_ in never]: never
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      graphql: {
        Args: {
          extensions?: Json
          operationName?: string
          query?: string
          variables?: Json
        }
        Returns: Json
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
  public: {
    Tables: {
      ai_runs: {
        Row: {
          analysis_id: string | null
          cost_usd: number
          created_at: string
          error: string | null
          id: string
          input_tokens: number
          lot_id: string | null
          model: string
          ok: boolean
          org_id: string | null
          output_tokens: number
          prompt_version: string
          stage: string
          updated_at: string
        }
        Insert: {
          analysis_id?: string | null
          cost_usd?: number
          created_at?: string
          error?: string | null
          id?: string
          input_tokens?: number
          lot_id?: string | null
          model: string
          ok?: boolean
          org_id?: string | null
          output_tokens?: number
          prompt_version: string
          stage: string
          updated_at?: string
        }
        Update: {
          analysis_id?: string | null
          cost_usd?: number
          created_at?: string
          error?: string | null
          id?: string
          input_tokens?: number
          lot_id?: string | null
          model?: string
          ok?: boolean
          org_id?: string | null
          output_tokens?: number
          prompt_version?: string
          stage?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "ai_runs_analysis_id_fkey"
            columns: ["analysis_id"]
            isOneToOne: false
            referencedRelation: "analyses"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "ai_runs_lot_id_fkey"
            columns: ["lot_id"]
            isOneToOne: false
            referencedRelation: "lots"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "ai_runs_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organisations"
            referencedColumns: ["id"]
          },
        ]
      }
      analyses: {
        Row: {
          auction_id: string
          cost_profile_id: string | null
          created_at: string
          created_by: string
          id: string
          org_id: string
          pdf_path: string | null
          premium_override_schedule: Json | null
          progress_pct: number
          source_type: string
          status: string
          updated_at: string
        }
        Insert: {
          auction_id: string
          cost_profile_id?: string | null
          created_at?: string
          created_by: string
          id?: string
          org_id: string
          pdf_path?: string | null
          premium_override_schedule?: Json | null
          progress_pct?: number
          source_type: string
          status?: string
          updated_at?: string
        }
        Update: {
          auction_id?: string
          cost_profile_id?: string | null
          created_at?: string
          created_by?: string
          id?: string
          org_id?: string
          pdf_path?: string | null
          premium_override_schedule?: Json | null
          progress_pct?: number
          source_type?: string
          status?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "analyses_auction_id_fkey"
            columns: ["auction_id"]
            isOneToOne: false
            referencedRelation: "auctions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "analyses_cost_profile_id_fkey"
            columns: ["cost_profile_id"]
            isOneToOne: false
            referencedRelation: "cost_profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "analyses_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "analyses_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organisations"
            referencedColumns: ["id"]
          },
        ]
      }
      analysis_lots: {
        Row: {
          analysis_id: string
          created_at: string
          id: string
          is_watchlisted: boolean
          lot_id: string
          opportunity_score: number | null
          status: string
          triage_high: number | null
          triage_low: number | null
          triage_max_bid: number | null
          updated_at: string
        }
        Insert: {
          analysis_id: string
          created_at?: string
          id?: string
          is_watchlisted?: boolean
          lot_id: string
          opportunity_score?: number | null
          status?: string
          triage_high?: number | null
          triage_low?: number | null
          triage_max_bid?: number | null
          updated_at?: string
        }
        Update: {
          analysis_id?: string
          created_at?: string
          id?: string
          is_watchlisted?: boolean
          lot_id?: string
          opportunity_score?: number | null
          status?: string
          triage_high?: number | null
          triage_low?: number | null
          triage_max_bid?: number | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "analysis_lots_analysis_id_fkey"
            columns: ["analysis_id"]
            isOneToOne: false
            referencedRelation: "analyses"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "analysis_lots_lot_id_fkey"
            columns: ["lot_id"]
            isOneToOne: false
            referencedRelation: "lots"
            referencedColumns: ["id"]
          },
        ]
      }
      auction_platforms: {
        Row: {
          created_at: string
          default_premium_gst: boolean
          default_premium_schedule: Json | null
          extractor_version: string
          id: string
          is_active: boolean
          name: string
          slug: string
          updated_at: string
          url_patterns: string[]
        }
        Insert: {
          created_at?: string
          default_premium_gst?: boolean
          default_premium_schedule?: Json | null
          extractor_version?: string
          id?: string
          is_active?: boolean
          name: string
          slug: string
          updated_at?: string
          url_patterns?: string[]
        }
        Update: {
          created_at?: string
          default_premium_gst?: boolean
          default_premium_schedule?: Json | null
          extractor_version?: string
          id?: string
          is_active?: boolean
          name?: string
          slug?: string
          updated_at?: string
          url_patterns?: string[]
        }
        Relationships: []
      }
      auctions: {
        Row: {
          closes_at: string | null
          created_at: string
          extracted_at: string | null
          id: string
          location_text: string | null
          platform_id: string
          premium_gst: boolean | null
          premium_schedule: Json | null
          premium_source: string
          raw_terms: string | null
          results_harvested_at: string | null
          results_harvested_count: number
          source_url: string | null
          title: string | null
          updated_at: string
        }
        Insert: {
          closes_at?: string | null
          created_at?: string
          extracted_at?: string | null
          id?: string
          location_text?: string | null
          platform_id: string
          premium_gst?: boolean | null
          premium_schedule?: Json | null
          premium_source?: string
          raw_terms?: string | null
          results_harvested_at?: string | null
          results_harvested_count?: number
          source_url?: string | null
          title?: string | null
          updated_at?: string
        }
        Update: {
          closes_at?: string | null
          created_at?: string
          extracted_at?: string | null
          id?: string
          location_text?: string | null
          platform_id?: string
          premium_gst?: boolean | null
          premium_schedule?: Json | null
          premium_source?: string
          raw_terms?: string | null
          results_harvested_at?: string | null
          results_harvested_count?: number
          source_url?: string | null
          title?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "auctions_platform_id_fkey"
            columns: ["platform_id"]
            isOneToOne: false
            referencedRelation: "auction_platforms"
            referencedColumns: ["id"]
          },
        ]
      }
      comparable_snapshots: {
        Row: {
          checked_at: string
          comparable_id: string
          created_at: string
          id: string
          price: number
          price_includes_gst: boolean | null
          status: string
          updated_at: string
        }
        Insert: {
          checked_at?: string
          comparable_id: string
          created_at?: string
          id?: string
          price: number
          price_includes_gst?: boolean | null
          status: string
          updated_at?: string
        }
        Update: {
          checked_at?: string
          comparable_id?: string
          created_at?: string
          id?: string
          price?: number
          price_includes_gst?: boolean | null
          status?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "comparable_snapshots_comparable_id_fkey"
            columns: ["comparable_id"]
            isOneToOne: false
            referencedRelation: "comparables"
            referencedColumns: ["id"]
          },
        ]
      }
      comparables: {
        Row: {
          condition: string | null
          created_at: string
          features: Json
          first_seen_at: string
          id: string
          location_text: string | null
          org_id: string | null
          provenance: string
          source_name: string
          source_type: string
          summary: string | null
          title: string
          updated_at: string
          url: string | null
          year: number | null
        }
        Insert: {
          condition?: string | null
          created_at?: string
          features?: Json
          first_seen_at?: string
          id?: string
          location_text?: string | null
          org_id?: string | null
          provenance: string
          source_name: string
          source_type: string
          summary?: string | null
          title: string
          updated_at?: string
          url?: string | null
          year?: number | null
        }
        Update: {
          condition?: string | null
          created_at?: string
          features?: Json
          first_seen_at?: string
          id?: string
          location_text?: string | null
          org_id?: string | null
          provenance?: string
          source_name?: string
          source_type?: string
          summary?: string | null
          title?: string
          updated_at?: string
          url?: string | null
          year?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "comparables_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organisations"
            referencedColumns: ["id"]
          },
        ]
      }
      cost_profiles: {
        Row: {
          created_at: string
          defaults: Json
          id: string
          is_default: boolean
          min_profit_amount: number | null
          min_return_pct: number | null
          name: string
          org_id: string
          profit_mode: string
          repair_mode: string
          repair_value: number | null
          target_profit_amount: number | null
          target_return_pct: number | null
          transport_base_fee: number | null
          transport_rate_per_km: number | null
          updated_at: string
        }
        Insert: {
          created_at?: string
          defaults?: Json
          id?: string
          is_default?: boolean
          min_profit_amount?: number | null
          min_return_pct?: number | null
          name: string
          org_id: string
          profit_mode?: string
          repair_mode?: string
          repair_value?: number | null
          target_profit_amount?: number | null
          target_return_pct?: number | null
          transport_base_fee?: number | null
          transport_rate_per_km?: number | null
          updated_at?: string
        }
        Update: {
          created_at?: string
          defaults?: Json
          id?: string
          is_default?: boolean
          min_profit_amount?: number | null
          min_return_pct?: number | null
          name?: string
          org_id?: string
          profit_mode?: string
          repair_mode?: string
          repair_value?: number | null
          target_profit_amount?: number | null
          target_return_pct?: number | null
          transport_base_fee?: number | null
          transport_rate_per_km?: number | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "cost_profiles_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organisations"
            referencedColumns: ["id"]
          },
        ]
      }
      lot_comparables: {
        Row: {
          adjusted_price: number
          adjustment_pct: number
          comparable_id: string
          created_at: string
          differences: Json
          excluded_by: string | null
          excluded_by_user: boolean
          exclusion_reason: string | null
          id: string
          identification_id: string
          match_level: string
          reason: string
          snapshot_id: string
          updated_at: string
          weight: number
        }
        Insert: {
          adjusted_price: number
          adjustment_pct?: number
          comparable_id: string
          created_at?: string
          differences?: Json
          excluded_by?: string | null
          excluded_by_user?: boolean
          exclusion_reason?: string | null
          id?: string
          identification_id: string
          match_level: string
          reason: string
          snapshot_id: string
          updated_at?: string
          weight: number
        }
        Update: {
          adjusted_price?: number
          adjustment_pct?: number
          comparable_id?: string
          created_at?: string
          differences?: Json
          excluded_by?: string | null
          excluded_by_user?: boolean
          exclusion_reason?: string | null
          id?: string
          identification_id?: string
          match_level?: string
          reason?: string
          snapshot_id?: string
          updated_at?: string
          weight?: number
        }
        Relationships: [
          {
            foreignKeyName: "lot_comparables_comparable_id_fkey"
            columns: ["comparable_id"]
            isOneToOne: false
            referencedRelation: "comparables"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lot_comparables_excluded_by_fkey"
            columns: ["excluded_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lot_comparables_identification_id_fkey"
            columns: ["identification_id"]
            isOneToOne: false
            referencedRelation: "lot_identifications"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lot_comparables_snapshot_id_fkey"
            columns: ["snapshot_id"]
            isOneToOne: false
            referencedRelation: "comparable_snapshots"
            referencedColumns: ["id"]
          },
        ]
      }
      lot_identifications: {
        Row: {
          ai_run_id: string | null
          analysis_id: string
          brand: string | null
          condition_notes: string | null
          confidence: number
          confirmed_by: string | null
          created_at: string
          id: string
          is_current: boolean
          lot_id: string
          model: string | null
          specs: Json
          stage: string
          updated_at: string
          year: number | null
        }
        Insert: {
          ai_run_id?: string | null
          analysis_id: string
          brand?: string | null
          condition_notes?: string | null
          confidence: number
          confirmed_by?: string | null
          created_at?: string
          id?: string
          is_current?: boolean
          lot_id: string
          model?: string | null
          specs?: Json
          stage: string
          updated_at?: string
          year?: number | null
        }
        Update: {
          ai_run_id?: string | null
          analysis_id?: string
          brand?: string | null
          condition_notes?: string | null
          confidence?: number
          confirmed_by?: string | null
          created_at?: string
          id?: string
          is_current?: boolean
          lot_id?: string
          model?: string | null
          specs?: Json
          stage?: string
          updated_at?: string
          year?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "lot_identifications_ai_run_id_fkey"
            columns: ["ai_run_id"]
            isOneToOne: false
            referencedRelation: "ai_runs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lot_identifications_analysis_id_fkey"
            columns: ["analysis_id"]
            isOneToOne: false
            referencedRelation: "analyses"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lot_identifications_confirmed_by_fkey"
            columns: ["confirmed_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lot_identifications_lot_id_fkey"
            columns: ["lot_id"]
            isOneToOne: false
            referencedRelation: "lots"
            referencedColumns: ["id"]
          },
        ]
      }
      lot_images: {
        Row: {
          created_at: string
          id: string
          lot_id: string
          position: number
          updated_at: string
          url: string
        }
        Insert: {
          created_at?: string
          id?: string
          lot_id: string
          position?: number
          updated_at?: string
          url: string
        }
        Update: {
          created_at?: string
          id?: string
          lot_id?: string
          position?: number
          updated_at?: string
          url?: string
        }
        Relationships: [
          {
            foreignKeyName: "lot_images_lot_id_fkey"
            columns: ["lot_id"]
            isOneToOne: false
            referencedRelation: "lots"
            referencedColumns: ["id"]
          },
        ]
      }
      lots: {
        Row: {
          auction_id: string
          bid_count: number | null
          closes_at: string | null
          created_at: string
          current_bid: number | null
          description: string | null
          did_not_sell: boolean | null
          gst_on_hammer: boolean | null
          id: string
          lat: number | null
          lng: number | null
          location_text: string | null
          lot_number: string
          raw: Json
          sold_at: string | null
          sold_price: number | null
          source_url: string | null
          title: string
          updated_at: string
        }
        Insert: {
          auction_id: string
          bid_count?: number | null
          closes_at?: string | null
          created_at?: string
          current_bid?: number | null
          description?: string | null
          did_not_sell?: boolean | null
          gst_on_hammer?: boolean | null
          id?: string
          lat?: number | null
          lng?: number | null
          location_text?: string | null
          lot_number: string
          raw?: Json
          sold_at?: string | null
          sold_price?: number | null
          source_url?: string | null
          title: string
          updated_at?: string
        }
        Update: {
          auction_id?: string
          bid_count?: number | null
          closes_at?: string | null
          created_at?: string
          current_bid?: number | null
          description?: string | null
          did_not_sell?: boolean | null
          gst_on_hammer?: boolean | null
          id?: string
          lat?: number | null
          lng?: number | null
          location_text?: string | null
          lot_number?: string
          raw?: Json
          sold_at?: string | null
          sold_price?: number | null
          source_url?: string | null
          title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "lots_auction_id_fkey"
            columns: ["auction_id"]
            isOneToOne: false
            referencedRelation: "auctions"
            referencedColumns: ["id"]
          },
        ]
      }
      org_settings: {
        Row: {
          created_at: string
          key: string
          lock_type: string
          org_id: string
          updated_at: string
          updated_by: string
          value: Json
        }
        Insert: {
          created_at?: string
          key: string
          lock_type?: string
          org_id: string
          updated_at?: string
          updated_by: string
          value: Json
        }
        Update: {
          created_at?: string
          key?: string
          lock_type?: string
          org_id?: string
          updated_at?: string
          updated_by?: string
          value?: Json
        }
        Relationships: [
          {
            foreignKeyName: "org_settings_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organisations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "org_settings_updated_by_fkey"
            columns: ["updated_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      organisation_members: {
        Row: {
          created_at: string
          org_id: string
          role: string
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          org_id: string
          role: string
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          org_id?: string
          role?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "organisation_members_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organisations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "organisation_members_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      organisations: {
        Row: {
          base_address: string | null
          base_lat: number | null
          base_lng: number | null
          created_at: string
          gst_registered: boolean
          id: string
          name: string
          plan: string
          stripe_customer_id: string | null
          updated_at: string
        }
        Insert: {
          base_address?: string | null
          base_lat?: number | null
          base_lng?: number | null
          created_at?: string
          gst_registered?: boolean
          id?: string
          name: string
          plan?: string
          stripe_customer_id?: string | null
          updated_at?: string
        }
        Update: {
          base_address?: string | null
          base_lat?: number | null
          base_lng?: number | null
          created_at?: string
          gst_registered?: boolean
          id?: string
          name?: string
          plan?: string
          stripe_customer_id?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      profiles: {
        Row: {
          alert_lead_minutes: number
          created_at: string
          default_org_id: string | null
          full_name: string | null
          id: string
          updated_at: string
        }
        Insert: {
          alert_lead_minutes?: number
          created_at?: string
          default_org_id?: string | null
          full_name?: string | null
          id: string
          updated_at?: string
        }
        Update: {
          alert_lead_minutes?: number
          created_at?: string
          default_org_id?: string | null
          full_name?: string | null
          id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "profiles_default_org_id_fkey"
            columns: ["default_org_id"]
            isOneToOne: false
            referencedRelation: "organisations"
            referencedColumns: ["id"]
          },
        ]
      }
      raw_extract: {
        Row: {
          auction_id: string
          created_at: string
          extractor_version: string
          fetched_at: string
          id: string
          page: number
          payload: Json
          source_url: string | null
          updated_at: string
        }
        Insert: {
          auction_id: string
          created_at?: string
          extractor_version: string
          fetched_at?: string
          id?: string
          page?: number
          payload: Json
          source_url?: string | null
          updated_at?: string
        }
        Update: {
          auction_id?: string
          created_at?: string
          extractor_version?: string
          fetched_at?: string
          id?: string
          page?: number
          payload?: Json
          source_url?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "raw_extract_auction_id_fkey"
            columns: ["auction_id"]
            isOneToOne: false
            referencedRelation: "auctions"
            referencedColumns: ["id"]
          },
        ]
      }
      terms_acceptances: {
        Row: {
          accepted_at: string
          created_at: string
          ip_address: unknown
          updated_at: string
          user_id: string
          version: string
        }
        Insert: {
          accepted_at?: string
          created_at?: string
          ip_address?: unknown
          updated_at?: string
          user_id: string
          version: string
        }
        Update: {
          accepted_at?: string
          created_at?: string
          ip_address?: unknown
          updated_at?: string
          user_id?: string
          version?: string
        }
        Relationships: [
          {
            foreignKeyName: "terms_acceptances_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "terms_acceptances_version_fkey"
            columns: ["version"]
            isOneToOne: false
            referencedRelation: "terms_versions"
            referencedColumns: ["version"]
          },
        ]
      }
      terms_versions: {
        Row: {
          content_url: string
          created_at: string
          is_material: boolean
          published_at: string
          updated_at: string
          version: string
        }
        Insert: {
          content_url: string
          created_at?: string
          is_material?: boolean
          published_at?: string
          updated_at?: string
          version: string
        }
        Update: {
          content_url?: string
          created_at?: string
          is_material?: boolean
          published_at?: string
          updated_at?: string
          version?: string
        }
        Relationships: []
      }
      usage_events: {
        Row: {
          analysis_id: string | null
          cost_usd: number
          created_at: string
          id: string
          org_id: string | null
          provider: string
          units: number
          updated_at: string
        }
        Insert: {
          analysis_id?: string | null
          cost_usd?: number
          created_at?: string
          id?: string
          org_id?: string | null
          provider: string
          units?: number
          updated_at?: string
        }
        Update: {
          analysis_id?: string | null
          cost_usd?: number
          created_at?: string
          id?: string
          org_id?: string | null
          provider?: string
          units?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "usage_events_analysis_id_fkey"
            columns: ["analysis_id"]
            isOneToOne: false
            referencedRelation: "analyses"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "usage_events_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organisations"
            referencedColumns: ["id"]
          },
        ]
      }
      user_preferences: {
        Row: {
          created_at: string
          key: string
          org_id: string
          updated_at: string
          user_id: string
          value: Json
        }
        Insert: {
          created_at?: string
          key: string
          org_id: string
          updated_at?: string
          user_id: string
          value: Json
        }
        Update: {
          created_at?: string
          key?: string
          org_id?: string
          updated_at?: string
          user_id?: string
          value?: Json
        }
        Relationships: [
          {
            foreignKeyName: "user_preferences_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organisations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_preferences_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      waitlist_signups: {
        Row: {
          converted_org_id: string | null
          created_at: string
          email: string
          founding_eligible: boolean
          id: string
          source: string | null
          updated_at: string
          utm: Json | null
        }
        Insert: {
          converted_org_id?: string | null
          created_at?: string
          email: string
          founding_eligible?: boolean
          id?: string
          source?: string | null
          updated_at?: string
          utm?: Json | null
        }
        Update: {
          converted_org_id?: string | null
          created_at?: string
          email?: string
          founding_eligible?: boolean
          id?: string
          source?: string | null
          updated_at?: string
          utm?: Json | null
        }
        Relationships: [
          {
            foreignKeyName: "waitlist_signups_converted_org_id_fkey"
            columns: ["converted_org_id"]
            isOneToOne: false
            referencedRelation: "organisations"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      can_edit_analysis: { Args: { target_analysis: string }; Returns: boolean }
      can_edit_identification: {
        Args: { target_identification: string }
        Returns: boolean
      }
      can_edit_org: { Args: { target_org: string }; Returns: boolean }
      create_organisation: { Args: { org_name: string }; Returns: string }
      is_org_admin: { Args: { target_org: string }; Returns: boolean }
      is_org_member: { Args: { target_org: string }; Returns: boolean }
      is_valid_premium_schedule: { Args: { schedule: Json }; Returns: boolean }
      org_role: { Args: { target_org: string }; Returns: string }
      owns_analysis: { Args: { target_analysis: string }; Returns: boolean }
      owns_identification: {
        Args: { target_identification: string }
        Returns: boolean
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  graphql_public: {
    Enums: {},
  },
  public: {
    Enums: {},
  },
} as const

