// Generated by pnpm db:types. Do not edit by hand.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  graphql_public: {
    Tables: {
      [_ in never]: never
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      graphql: {
        Args: {
          extensions?: Json
          operationName?: string
          query?: string
          variables?: Json
        }
        Returns: Json
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
  public: {
    Tables: {
      analyses: {
        Row: {
          auction_id: string
          cost_profile_id: string | null
          created_at: string
          created_by: string
          id: string
          org_id: string
          pdf_path: string | null
          premium_override_pct: number | null
          progress_pct: number
          source_type: string
          status: string
          updated_at: string
        }
        Insert: {
          auction_id: string
          cost_profile_id?: string | null
          created_at?: string
          created_by: string
          id?: string
          org_id: string
          pdf_path?: string | null
          premium_override_pct?: number | null
          progress_pct?: number
          source_type: string
          status?: string
          updated_at?: string
        }
        Update: {
          auction_id?: string
          cost_profile_id?: string | null
          created_at?: string
          created_by?: string
          id?: string
          org_id?: string
          pdf_path?: string | null
          premium_override_pct?: number | null
          progress_pct?: number
          source_type?: string
          status?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "analyses_auction_id_fkey"
            columns: ["auction_id"]
            isOneToOne: false
            referencedRelation: "auctions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "analyses_cost_profile_id_fkey"
            columns: ["cost_profile_id"]
            isOneToOne: false
            referencedRelation: "cost_profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "analyses_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "analyses_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organisations"
            referencedColumns: ["id"]
          },
        ]
      }
      analysis_lots: {
        Row: {
          analysis_id: string
          created_at: string
          id: string
          is_watchlisted: boolean
          lot_id: string
          opportunity_score: number | null
          status: string
          triage_high: number | null
          triage_low: number | null
          triage_max_bid: number | null
          updated_at: string
        }
        Insert: {
          analysis_id: string
          created_at?: string
          id?: string
          is_watchlisted?: boolean
          lot_id: string
          opportunity_score?: number | null
          status?: string
          triage_high?: number | null
          triage_low?: number | null
          triage_max_bid?: number | null
          updated_at?: string
        }
        Update: {
          analysis_id?: string
          created_at?: string
          id?: string
          is_watchlisted?: boolean
          lot_id?: string
          opportunity_score?: number | null
          status?: string
          triage_high?: number | null
          triage_low?: number | null
          triage_max_bid?: number | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "analysis_lots_analysis_id_fkey"
            columns: ["analysis_id"]
            isOneToOne: false
            referencedRelation: "analyses"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "analysis_lots_lot_id_fkey"
            columns: ["lot_id"]
            isOneToOne: false
            referencedRelation: "lots"
            referencedColumns: ["id"]
          },
        ]
      }
      auction_platforms: {
        Row: {
          created_at: string
          default_premium_gst: boolean
          default_premium_pct: number | null
          extractor_version: string
          id: string
          is_active: boolean
          name: string
          slug: string
          updated_at: string
          url_patterns: string[]
        }
        Insert: {
          created_at?: string
          default_premium_gst?: boolean
          default_premium_pct?: number | null
          extractor_version?: string
          id?: string
          is_active?: boolean
          name: string
          slug: string
          updated_at?: string
          url_patterns?: string[]
        }
        Update: {
          created_at?: string
          default_premium_gst?: boolean
          default_premium_pct?: number | null
          extractor_version?: string
          id?: string
          is_active?: boolean
          name?: string
          slug?: string
          updated_at?: string
          url_patterns?: string[]
        }
        Relationships: []
      }
      auctions: {
        Row: {
          closes_at: string | null
          created_at: string
          extracted_at: string | null
          id: string
          location_text: string | null
          platform_id: string
          premium_gst: boolean | null
          premium_pct: number | null
          premium_source: string
          raw_terms: string | null
          source_url: string | null
          title: string | null
          updated_at: string
        }
        Insert: {
          closes_at?: string | null
          created_at?: string
          extracted_at?: string | null
          id?: string
          location_text?: string | null
          platform_id: string
          premium_gst?: boolean | null
          premium_pct?: number | null
          premium_source?: string
          raw_terms?: string | null
          source_url?: string | null
          title?: string | null
          updated_at?: string
        }
        Update: {
          closes_at?: string | null
          created_at?: string
          extracted_at?: string | null
          id?: string
          location_text?: string | null
          platform_id?: string
          premium_gst?: boolean | null
          premium_pct?: number | null
          premium_source?: string
          raw_terms?: string | null
          source_url?: string | null
          title?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "auctions_platform_id_fkey"
            columns: ["platform_id"]
            isOneToOne: false
            referencedRelation: "auction_platforms"
            referencedColumns: ["id"]
          },
        ]
      }
      cost_profiles: {
        Row: {
          created_at: string
          defaults: Json
          id: string
          is_default: boolean
          min_profit_amount: number | null
          min_return_pct: number | null
          name: string
          org_id: string
          profit_mode: string
          repair_mode: string
          repair_value: number | null
          target_profit_amount: number | null
          target_return_pct: number | null
          transport_base_fee: number | null
          transport_rate_per_km: number | null
          updated_at: string
        }
        Insert: {
          created_at?: string
          defaults?: Json
          id?: string
          is_default?: boolean
          min_profit_amount?: number | null
          min_return_pct?: number | null
          name: string
          org_id: string
          profit_mode?: string
          repair_mode?: string
          repair_value?: number | null
          target_profit_amount?: number | null
          target_return_pct?: number | null
          transport_base_fee?: number | null
          transport_rate_per_km?: number | null
          updated_at?: string
        }
        Update: {
          created_at?: string
          defaults?: Json
          id?: string
          is_default?: boolean
          min_profit_amount?: number | null
          min_return_pct?: number | null
          name?: string
          org_id?: string
          profit_mode?: string
          repair_mode?: string
          repair_value?: number | null
          target_profit_amount?: number | null
          target_return_pct?: number | null
          transport_base_fee?: number | null
          transport_rate_per_km?: number | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "cost_profiles_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organisations"
            referencedColumns: ["id"]
          },
        ]
      }
      lot_images: {
        Row: {
          created_at: string
          id: string
          lot_id: string
          position: number
          updated_at: string
          url: string
        }
        Insert: {
          created_at?: string
          id?: string
          lot_id: string
          position?: number
          updated_at?: string
          url: string
        }
        Update: {
          created_at?: string
          id?: string
          lot_id?: string
          position?: number
          updated_at?: string
          url?: string
        }
        Relationships: [
          {
            foreignKeyName: "lot_images_lot_id_fkey"
            columns: ["lot_id"]
            isOneToOne: false
            referencedRelation: "lots"
            referencedColumns: ["id"]
          },
        ]
      }
      lots: {
        Row: {
          auction_id: string
          closes_at: string | null
          created_at: string
          current_bid: number | null
          description: string | null
          gst_on_hammer: boolean | null
          id: string
          lat: number | null
          lng: number | null
          location_text: string | null
          lot_number: string
          raw: Json
          source_url: string | null
          title: string
          updated_at: string
        }
        Insert: {
          auction_id: string
          closes_at?: string | null
          created_at?: string
          current_bid?: number | null
          description?: string | null
          gst_on_hammer?: boolean | null
          id?: string
          lat?: number | null
          lng?: number | null
          location_text?: string | null
          lot_number: string
          raw?: Json
          source_url?: string | null
          title: string
          updated_at?: string
        }
        Update: {
          auction_id?: string
          closes_at?: string | null
          created_at?: string
          current_bid?: number | null
          description?: string | null
          gst_on_hammer?: boolean | null
          id?: string
          lat?: number | null
          lng?: number | null
          location_text?: string | null
          lot_number?: string
          raw?: Json
          source_url?: string | null
          title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "lots_auction_id_fkey"
            columns: ["auction_id"]
            isOneToOne: false
            referencedRelation: "auctions"
            referencedColumns: ["id"]
          },
        ]
      }
      org_settings: {
        Row: {
          created_at: string
          key: string
          lock_type: string
          org_id: string
          updated_at: string
          updated_by: string
          value: Json
        }
        Insert: {
          created_at?: string
          key: string
          lock_type?: string
          org_id: string
          updated_at?: string
          updated_by: string
          value: Json
        }
        Update: {
          created_at?: string
          key?: string
          lock_type?: string
          org_id?: string
          updated_at?: string
          updated_by?: string
          value?: Json
        }
        Relationships: [
          {
            foreignKeyName: "org_settings_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organisations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "org_settings_updated_by_fkey"
            columns: ["updated_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      organisation_members: {
        Row: {
          created_at: string
          org_id: string
          role: string
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          org_id: string
          role: string
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          org_id?: string
          role?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "organisation_members_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organisations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "organisation_members_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      organisations: {
        Row: {
          base_address: string | null
          base_lat: number | null
          base_lng: number | null
          created_at: string
          gst_registered: boolean
          id: string
          name: string
          plan: string
          stripe_customer_id: string | null
          updated_at: string
        }
        Insert: {
          base_address?: string | null
          base_lat?: number | null
          base_lng?: number | null
          created_at?: string
          gst_registered?: boolean
          id?: string
          name: string
          plan?: string
          stripe_customer_id?: string | null
          updated_at?: string
        }
        Update: {
          base_address?: string | null
          base_lat?: number | null
          base_lng?: number | null
          created_at?: string
          gst_registered?: boolean
          id?: string
          name?: string
          plan?: string
          stripe_customer_id?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      profiles: {
        Row: {
          alert_lead_minutes: number
          created_at: string
          default_org_id: string | null
          full_name: string | null
          id: string
          updated_at: string
        }
        Insert: {
          alert_lead_minutes?: number
          created_at?: string
          default_org_id?: string | null
          full_name?: string | null
          id: string
          updated_at?: string
        }
        Update: {
          alert_lead_minutes?: number
          created_at?: string
          default_org_id?: string | null
          full_name?: string | null
          id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "profiles_default_org_id_fkey"
            columns: ["default_org_id"]
            isOneToOne: false
            referencedRelation: "organisations"
            referencedColumns: ["id"]
          },
        ]
      }
      raw_extract: {
        Row: {
          auction_id: string
          created_at: string
          extractor_version: string
          fetched_at: string
          id: string
          page: number
          payload: Json
          source_url: string | null
          updated_at: string
        }
        Insert: {
          auction_id: string
          created_at?: string
          extractor_version: string
          fetched_at?: string
          id?: string
          page?: number
          payload: Json
          source_url?: string | null
          updated_at?: string
        }
        Update: {
          auction_id?: string
          created_at?: string
          extractor_version?: string
          fetched_at?: string
          id?: string
          page?: number
          payload?: Json
          source_url?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "raw_extract_auction_id_fkey"
            columns: ["auction_id"]
            isOneToOne: false
            referencedRelation: "auctions"
            referencedColumns: ["id"]
          },
        ]
      }
      terms_acceptances: {
        Row: {
          accepted_at: string
          created_at: string
          ip_address: unknown
          updated_at: string
          user_id: string
          version: string
        }
        Insert: {
          accepted_at?: string
          created_at?: string
          ip_address?: unknown
          updated_at?: string
          user_id: string
          version: string
        }
        Update: {
          accepted_at?: string
          created_at?: string
          ip_address?: unknown
          updated_at?: string
          user_id?: string
          version?: string
        }
        Relationships: [
          {
            foreignKeyName: "terms_acceptances_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "terms_acceptances_version_fkey"
            columns: ["version"]
            isOneToOne: false
            referencedRelation: "terms_versions"
            referencedColumns: ["version"]
          },
        ]
      }
      terms_versions: {
        Row: {
          content_url: string
          created_at: string
          is_material: boolean
          published_at: string
          updated_at: string
          version: string
        }
        Insert: {
          content_url: string
          created_at?: string
          is_material?: boolean
          published_at?: string
          updated_at?: string
          version: string
        }
        Update: {
          content_url?: string
          created_at?: string
          is_material?: boolean
          published_at?: string
          updated_at?: string
          version?: string
        }
        Relationships: []
      }
      user_preferences: {
        Row: {
          created_at: string
          key: string
          org_id: string
          updated_at: string
          user_id: string
          value: Json
        }
        Insert: {
          created_at?: string
          key: string
          org_id: string
          updated_at?: string
          user_id: string
          value: Json
        }
        Update: {
          created_at?: string
          key?: string
          org_id?: string
          updated_at?: string
          user_id?: string
          value?: Json
        }
        Relationships: [
          {
            foreignKeyName: "user_preferences_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organisations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_preferences_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      waitlist_signups: {
        Row: {
          converted_org_id: string | null
          created_at: string
          email: string
          founding_eligible: boolean
          id: string
          source: string | null
          updated_at: string
          utm: Json | null
        }
        Insert: {
          converted_org_id?: string | null
          created_at?: string
          email: string
          founding_eligible?: boolean
          id?: string
          source?: string | null
          updated_at?: string
          utm?: Json | null
        }
        Update: {
          converted_org_id?: string | null
          created_at?: string
          email?: string
          founding_eligible?: boolean
          id?: string
          source?: string | null
          updated_at?: string
          utm?: Json | null
        }
        Relationships: [
          {
            foreignKeyName: "waitlist_signups_converted_org_id_fkey"
            columns: ["converted_org_id"]
            isOneToOne: false
            referencedRelation: "organisations"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      can_edit_analysis: { Args: { target_analysis: string }; Returns: boolean }
      can_edit_org: { Args: { target_org: string }; Returns: boolean }
      create_organisation: { Args: { org_name: string }; Returns: string }
      is_org_admin: { Args: { target_org: string }; Returns: boolean }
      is_org_member: { Args: { target_org: string }; Returns: boolean }
      org_role: { Args: { target_org: string }; Returns: string }
      owns_analysis: { Args: { target_analysis: string }; Returns: boolean }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  graphql_public: {
    Enums: {},
  },
  public: {
    Enums: {},
  },
} as const

